
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frame1.java
 *
 * Created on 07/11/2011, 07:39:34 PM
 */
/**
 *
 * @author José Oberto
 */
public class frame1 extends javax.swing.JFrame {

    /** Creates new form frame1 */
    public frame1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
cronometrar();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frame1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public void cronometrar(){

     a.start();


    }


           Thread a =  new Thread(){

                @Override
                public void run() {


        int hor = Integer.parseInt(JOptionPane.showInputDialog("Introduzca la hora"));
        int min = Integer.parseInt(JOptionPane.showInputDialog("Introduzca ea min"));
        int seg = Integer.parseInt(JOptionPane.showInputDialog("Introduzca ea seg"));

        while(seg > 59){
            seg-=59;
            min++;
        }
        while(min > 59){
            min-=59;
            hor++;
        }

        String h,m,s;
        h = String.valueOf(hor).length() > 1 ? String.valueOf(hor) : "0"+ String.valueOf(hor);
        m = String.valueOf(min).length() > 1 ? String.valueOf(min) : "0"+ String.valueOf(min);
        s = String.valueOf(seg).length() > 1 ? String.valueOf(seg) : "0"+ String.valueOf(seg);
        jLabel1.setText("Cronometro para: "+h+":"+m+":"+s);
        while(seg>0||min>0||hor>0){
            try{
                Thread.sleep(1*1000);
            }catch(InterruptedException e){}
            seg--;
            if(seg < 0){
                min--;
                seg=59;
                if(min<0){
                    hor--;
                    min=59;
                }
            }
            h = String.valueOf(hor).length() > 1 ? String.valueOf(hor) : "0"+ String.valueOf(hor);
            m = String.valueOf(min).length() > 1 ? String.valueOf(min) : "0"+ String.valueOf(min);
            s = String.valueOf(seg).length() > 1 ? String.valueOf(seg) : "0"+ String.valueOf(seg);



                jLabel1.setText("Faltan: "+h+":"+m+":"+s);



                }

                jLabel1.setText("FIN DE LA CUENTA");





            }};





        }











